// <auto-generated />
using System;
using LeafScan.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeafScan.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeafScan.Domain.Entities.AiChatbot", b =>
                {
                    b.Property<int>("ChatbotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatbotId"));

                    b.Property<string>("Capabilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ChatbotId");

                    b.ToTable("AiChatbots");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.ChatSession", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatId"));

                    b.Property<int>("ChatbotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Messages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChatId");

                    b.HasIndex("ChatbotId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.Diagnosis", b =>
                {
                    b.Property<int>("DiagnosisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiagnosisId"));

                    b.Property<DateTime>("DiagnosedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DiagnosedByAi")
                        .HasColumnType("bit");

                    b.Property<int>("DiseaseId")
                        .HasColumnType("int");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.HasKey("DiagnosisId");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("ImageId");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.Disease", b =>
                {
                    b.Property<int>("DiseaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiseaseId"));

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SeverityLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Symptoms")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiseaseId");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("Status");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.Plant", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantId"));

                    b.Property<string>("PlantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SoilType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Species")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlantId");

                    b.HasIndex("UserId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.PlantImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImageId");

                    b.HasIndex("PlantId");

                    b.HasIndex("UserId");

                    b.ToTable("PlantImages");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<int?>("ChatbotId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReportType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReportId");

                    b.HasIndex("ChatbotId");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.SoilData", b =>
                {
                    b.Property<int>("SoilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoilId"));

                    b.Property<decimal?>("MoistureLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Nitrogen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PhLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Phosphorus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Potassium")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SoilId");

                    b.HasIndex("PlantId");

                    b.ToTable("SoilData");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.Climate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Climates");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.Crop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.CropRequirement", b =>
                {
                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<decimal>("FertilizerKgPerAcre")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WaterLitersPerAcrePerWeek")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CropId");

                    b.ToTable("CropRequirements");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.CropSoilClimate", b =>
                {
                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<int>("SoilTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ClimateId")
                        .HasColumnType("int");

                    b.HasKey("CropId", "SoilTypeId", "ClimateId");

                    b.HasIndex("ClimateId");

                    b.HasIndex("SoilTypeId");

                    b.ToTable("CropSoilClimates");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.SoilType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SoilTypes");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.UserChat", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ChatId");

                    b.HasIndex("ChatId");

                    b.ToTable("UserChats");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.UserPlantImage", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ImageId");

                    b.HasIndex("ImageId");

                    b.ToTable("UserPlantImages");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.ChatSession", b =>
                {
                    b.HasOne("LeafScan.Domain.Entities.AiChatbot", "Chatbot")
                        .WithMany("ChatSessions")
                        .HasForeignKey("ChatbotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeafScan.Domain.Entities.User", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chatbot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.Diagnosis", b =>
                {
                    b.HasOne("LeafScan.Domain.Entities.Disease", "Disease")
                        .WithMany("Diagnoses")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeafScan.Domain.Entities.PlantImage", "PlantImage")
                        .WithMany("Diagnoses")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("PlantImage");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.Message", b =>
                {
                    b.HasOne("LeafScan.Domain.Entities.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.Plant", b =>
                {
                    b.HasOne("LeafScan.Domain.Entities.User", "User")
                        .WithMany("Plants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.PlantImage", b =>
                {
                    b.HasOne("LeafScan.Domain.Entities.Plant", "Plant")
                        .WithMany("PlantImages")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeafScan.Domain.Entities.User", "User")
                        .WithMany("PlantImages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Plant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.Report", b =>
                {
                    b.HasOne("LeafScan.Domain.Entities.AiChatbot", "Chatbot")
                        .WithMany("Reports")
                        .HasForeignKey("ChatbotId");

                    b.HasOne("LeafScan.Domain.Entities.Diagnosis", "Diagnosis")
                        .WithMany("Reports")
                        .HasForeignKey("DiagnosisId");

                    b.HasOne("LeafScan.Domain.Entities.User", "Manager")
                        .WithMany("ReportsAsManager")
                        .HasForeignKey("ManagerId");

                    b.Navigation("Chatbot");

                    b.Navigation("Diagnosis");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.CropRequirement", b =>
                {
                    b.HasOne("LeafScan.Domain.Entities.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.CropSoilClimate", b =>
                {
                    b.HasOne("LeafScan.Domain.Entities.Climate", "Climate")
                        .WithMany()
                        .HasForeignKey("ClimateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeafScan.Domain.Entities.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeafScan.Domain.Entities.SoilType", "SoilType")
                        .WithMany()
                        .HasForeignKey("SoilTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Climate");

                    b.Navigation("Crop");

                    b.Navigation("SoilType");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.SoilData", b =>
                {
                    b.HasOne("LeafScan.Domain.Entities.Plant", "Plant")
                        .WithMany("SoilDataRecords")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.UserChat", b =>
                {
                    b.HasOne("LeafScan.Domain.Entities.ChatSession", "ChatSession")
                        .WithMany("UserChats")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LeafScan.Domain.Entities.User", "User")
                        .WithMany("UserChats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.UserPlantImage", b =>
                {
                    b.HasOne("LeafScan.Domain.Entities.PlantImage", "PlantImage")
                        .WithMany("UserPlantImages")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LeafScan.Domain.Entities.User", "User")
                        .WithMany("UserPlantImages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantImage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.AiChatbot", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.ChatSession", b =>
                {
                    b.Navigation("UserChats");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.Diagnosis", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.Disease", b =>
                {
                    b.Navigation("Diagnoses");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.Plant", b =>
                {
                    b.Navigation("PlantImages");

                    b.Navigation("SoilDataRecords");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.PlantImage", b =>
                {
                    b.Navigation("Diagnoses");

                    b.Navigation("UserPlantImages");
                });

            modelBuilder.Entity("LeafScan.Domain.Entities.User", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("PlantImages");

                    b.Navigation("Plants");

                    b.Navigation("ReportsAsManager");

                    b.Navigation("ChatSessions");

                    b.Navigation("UserChats");

                    b.Navigation("UserPlantImages");
                });
#pragma warning restore 612, 618
        }
    }
}
